//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralama
    {
        public int kiraId { get; set; }
        public string aracPlakaNo { get; set; }
        public System.DateTime kiraBasGun { get; set; }
        public System.DateTime kiraSonGun { get; set; }
        public int kiraUyeId { get; set; }
        public int kiraAracId { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
